CREATE TABLE IF NOT EXISTS USERS (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_authorities_user FOREIGN KEY (username) REFERENCES USERS (username),
    UNIQUE (username, authority)
);

CREATE TABLE IF NOT EXISTS USER_DETAILS (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    date_of_birth DATE,
    email VARCHAR(100),
    sport VARCHAR(20),
    favorite_team VARCHAR(20),
    total_score BIGINT DEFAULT 0,
    CONSTRAINT fk_details_user FOREIGN KEY (username) REFERENCES USERS (username)
);

CREATE TABLE IF NOT EXISTS REVIEWS(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id INT REFERENCES USERS(id),
    text VARCHAR(500),
    score INT
);

CREATE TABLE IF NOT EXISTS GIORNATE(
    matchday INT PRIMARY KEY
);

DROP TABLE IF EXISTS prizes_types;

CREATE TABLE IF NOT EXISTS prize_types (
     id BIGINT AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS prizes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    prize_type_id BIGINT NOT NULL,
    awarded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_prize_type FOREIGN KEY (prize_type_id) REFERENCES prize_types(id)
);

INSERT INTO prize_types (name) VALUES
   ('Biglietto Partita Squadra del cuore'),
   ('Magletta Giocatore Squadra del cuore'),
   ('Serata in pizzera con la squadra del cuore');

DROP TABLE IF EXISTS news;

CREATE TABLE news (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  text VARCHAR(500) NOT NULL
);

INSERT INTO news (text) VALUES
    ('A breve inizierà la partita tra Trento e Suedtirol!'),
    ('Partecipa al nostro concorso per vincere una cena con la tua squadra del cuore!'),
    ('Cartellino rosso per Mario Rossi: escluso dal campionato'),
    ('Allerta maltempo: rischio cancellazione partite nelle prossime settimane'),
    ('Il presidente della federazione annuncia imminenti modifiche al regolamento');
